/*
 * API routes list
 */

export const api_routes = {
  account: {
    get: "/api/v1/account",
    update: "/api/v1/account/update",
    update_password: "/api/v1/account/password",
    refresh: "/api/v1/account/refresh",
    logout: "/api/v1/account/logout",
  },
  auth: {
    login_with_phone_password: "/api/v1/auth/login-with-phone-password",
    login_with_email_password: "/api/v1/auth/login-with-email-password",
    register: "/api/v1/auth/register",
    forgot_password_email: "/api/v1/auth/forgot-password-email",
    forgot_password_phone: "/api/v1/auth/forgot-password-phone",
    reset_password: "/api/v1/auth/reset-password",
  },
  role: {
    paginate: "/api/v1/roles/paginate",
  },
  user: {
    paginate: "/api/v1/users/paginate",
    view: "/api/v1/users/view",
    create: "/api/v1/users/create",
    update: "/api/v1/users/update",
    delete: "/api/v1/users/delete",
    toggle_status: "/api/v1/users/status",
    toggle_verification: "/api/v1/users/verify",
    excel: "/api/v1/users/excel",
  },
  charge: {
    paginate: "/api/v1/charges/paginate",
    view: "/api/v1/charges/view",
    create: "/api/v1/charges/create",
    update: "/api/v1/charges/update",
    delete: "/api/v1/charges/delete",
    toggle_status: "/api/v1/charges/status",
    slug: "/api/v1/charges/slug",
    excel: "/api/v1/charges/excel",
  },
  tax: {
    paginate: "/api/v1/taxes/paginate",
    view: "/api/v1/taxes/view",
    create: "/api/v1/taxes/create",
    update: "/api/v1/taxes/update",
    delete: "/api/v1/taxes/delete",
    toggle_status: "/api/v1/taxes/status",
    slug: "/api/v1/taxes/slug",
    excel: "/api/v1/taxes/excel",
  },
  testimonial: {
    paginate: "/api/v1/testimonials/paginate",
    view: "/api/v1/testimonials/view",
    create: "/api/v1/testimonials/create",
    update: "/api/v1/testimonials/update",
    delete: "/api/v1/testimonials/delete",
    toggle_status: "/api/v1/testimonials/status",
    excel: "/api/v1/testimonials/excel",
  },
  delivery_slot: {
    paginate: "/api/v1/delivery-slots/paginate",
    view: "/api/v1/delivery-slots/view",
    create: "/api/v1/delivery-slots/create",
    update: "/api/v1/delivery-slots/update",
    delete: "/api/v1/delivery-slots/delete",
    toggle_status: "/api/v1/delivery-slots/status",
    excel: "/api/v1/delivery-slots/excel",
  },
  blog: {
    paginate: "/api/v1/blogs/paginate",
    view: "/api/v1/blogs/view",
    create: "/api/v1/blogs/create",
    update: "/api/v1/blogs/update",
    delete: "/api/v1/blogs/delete",
    toggle_status: "/api/v1/blogs/status",
    slug: "/api/v1/blogs/slug",
    excel: "/api/v1/blogs/excel",
  },
  category: {
    paginate: "/api/v1/categories/paginate",
    view: "/api/v1/categories/view",
    create: "/api/v1/categories/create",
    update: "/api/v1/categories/update",
    delete: "/api/v1/categories/delete",
    toggle_status: "/api/v1/categories/status",
    slug: "/api/v1/categories/slug",
    excel: "/api/v1/categories/excel",
  },
  sub_category: {
    paginate: "/api/v1/sub-categories/paginate",
    view: "/api/v1/sub-categories/view",
    create: "/api/v1/sub-categories/create",
    update: "/api/v1/sub-categories/update",
    delete: "/api/v1/sub-categories/delete",
    toggle_status: "/api/v1/sub-categories/status",
    slug: "/api/v1/sub-categories/slug",
    excel: "/api/v1/sub-categories/excel",
  },
  product: {
    paginate: "/api/v1/products/paginate",
    view: "/api/v1/products/view",
    create: "/api/v1/products/create",
    update: "/api/v1/products/update",
    delete: "/api/v1/products/delete",
    toggle_status: "/api/v1/products/status",
    slug: "/api/v1/products/slug",
    excel: "/api/v1/products/excel",
  },
  legal_content: {
    paginate: "/api/v1/legal-contents/paginate",
    view: "/api/v1/legal-contents/view",
    create: "/api/v1/legal-contents/create",
    update: "/api/v1/legal-contents/update",
    delete: "/api/v1/legal-contents/delete",
    toggle_status: "/api/v1/legal-contents/status",
    slug: "/api/v1/legal-contents/slug",
    excel: "/api/v1/legal-contents/excel",
  },
  feature: {
    paginate: "/api/v1/features/paginate",
    view: "/api/v1/features/view",
    create: "/api/v1/features/create",
    update: "/api/v1/features/update",
    delete: "/api/v1/features/delete",
    toggle_status: "/api/v1/features/status",
    excel: "/api/v1/features/excel",
  },
  banner: {
    paginate: "/api/v1/banners/paginate",
    view: "/api/v1/banners/view",
    create: "/api/v1/banners/create",
    update: "/api/v1/banners/update",
    delete: "/api/v1/banners/delete",
    toggle_status: "/api/v1/banners/status",
    excel: "/api/v1/banners/excel",
  },
  about_section: {
    paginate: "/api/v1/about-sections/paginate",
    view: "/api/v1/about-sections/view",
    create: "/api/v1/about-sections/create",
    update: "/api/v1/about-sections/update",
    delete: "/api/v1/about-sections/delete",
    toggle_status: "/api/v1/about-sections/status",
    excel: "/api/v1/about-sections/excel",
  },
  payment_option: {
    paginate: "/api/v1/payment-options/paginate",
    view: "/api/v1/payment-options/view",
    toggle_status: "/api/v1/payment-options/status",
    excel: "/api/v1/payment-options/excel",
  },
  contact_form_enquiry: {
    paginate: "/api/v1/contact-form-enquiries/paginate",
    view: "/api/v1/contact-form-enquiries/view",
    delete: "/api/v1/contact-form-enquiries/delete",
    excel: "/api/v1/contact-form-enquiries/excel",
  },
  text_editor_image: {
    create: "/api/v1/texteditor-images/create",
  },
} as const;
